export const colors = {
    "default": "bg-lime-400",
    "secondary": "bg-sky-400",
    "types.normal": "bg-neutral-500",
    "types.fighting": "bg-rose-700",
    "types.flying": "bg-blue-400",
    "types.poison": "bg-fuchsia-800",
    "types.ground": "bg-taupe-500",
    "types.rock": "bg-olive-500",
    "types.bug": "bg-lime-700",
    "types.ghost": "bg-violet-900",
    "types.steel": "bg-slate-400",
    "types.fire": "bg-amber-700",
    "types.water": "bg-blue-600",
    "types.grass": "bg-emerald-700",
    "types.electric": "bg-yellow-400",
    "types.psychic": "bg-rose-400",
    "types.ice": "bg-cyan-300",
    "types.dragon": "bg-indigo-500",
    "types.dark": "bg-zinc-800",
    "types.fairy": "bg-fuchsia-400"
};

export const paleColors = {
    "default": "bg-mauve-800",
    "types.normal": "bg-neutral-500/40",
    "types.fighting": "bg-rose-700/40",
    "types.flying": "bg-blue-400/40",
    "types.poison": "bg-fuchsia-800/40",
    "types.ground": "bg-taupe-500/40",
    "types.rock": "bg-olive-500/40",
    "types.bug": "bg-lime-700/40",
    "types.ghost": "bg-violet-900/40",
    "types.steel": "bg-slate-400/40",
    "types.fire": "bg-amber-700/40",
    "types.water": "bg-blue-600/40",
    "types.grass": "bg-emerald-700/40",
    "types.electric": "bg-yellow-400/40",
    "types.psychic": "bg-rose-400/40",
    "types.ice": "bg-cyan-300/40",
    "types.dragon": "bg-indigo-500/40",
    "types.dark": "bg-zinc-700/40",
    "types.fairy": "bg-fuchsia-400/40"
};

export const textColors = {
    "lightMode": "text-zinc-900",
    "darkMode": "text-zinc-200",
    "types.normal": "text-zinc-200",
    "types.fighting": "text-zinc-200",
    "types.flying": "text-zinc-900",
    "types.poison": "text-zinc-200",
    "types.ground": "text-zinc-200",
    "types.rock": "text-zinc-200",
    "types.bug": "text-zinc-200",
    "types.ghost": "text-zinc-200",
    "types.steel": "text-zinc-900",
    "types.fire": "text-zinc-200",
    "types.water": "text-zinc-200",
    "types.grass": "text-zinc-200",
    "types.electric": "text-zinc-900",
    "types.psychic": "text-zinc-900",
    "types.ice": "text-zinc-900",
    "types.dragon": "text-zinc-200",
    "types.dark": "text-zinc-200",
    "types.fairy": "text-zinc-900",
};

export const textColorsMain = {
    "default": "text-mauve-800",
    "types.normal": "text-neutral-500",
    "types.fighting": "text-rose-700",
    "types.flying": "text-blue-400",
    "types.poison": "text-fuchsia-600",
    "types.ground": "text-taupe-400",
    "types.rock": "text-olive-500",
    "types.bug": "text-lime-600",
    "types.ghost": "text-violet-600",
    "types.steel": "text-slate-400",
    "types.fire": "text-amber-600",
    "types.water": "text-blue-600",
    "types.grass": "text-emerald-500",
    "types.electric": "text-yellow-400",
    "types.psychic": "text-rose-400",
    "types.ice": "text-cyan-300",
    "types.dragon": "text-indigo-500",
    "types.dark": "text-zinc-400",
    "types.fairy": "text-fuchsia-400"
};