import type { PkmnType } from "./interfaces";

export const types: PkmnType[] = [
    {
        id: 0,
        name: "types.normal",
        description: "types.normalDesc",
        effective: [],
        weak: [1],
        notEffective: [5, 8],
        resists: [],
        noEffectTo: [7],
        notAffectedBy: [7],
    },
    {
        id: 1,
        name: "types.fighting",
        description: "types.fightingDesc",
        effective: [0, 14, 5, 16, 8],
        weak: [2, 13, 17],
        notEffective: [3, 2, 13, 6, 17],
        resists: [6, 5, 16],
        noEffectTo: [7],
        notAffectedBy: [],
    },
    {
        id: 2,
        name: "types.flying",
        description: "types.flyingDesc",
        effective: [6, 11, 1],
        weak: [14, 5, 12],
        notEffective: [12, 5, 8],
        resists: [11, 1, 6],
        noEffectTo: [],
        notAffectedBy: [4],
    },
    {
        id: 3,
        name: "types.poison",
        description: "types.poisonDesc",
        effective: [11, 17],
        weak: [4, 13],
        notEffective: [3, 4, 5, 7],
        resists: [11, 1, 3, 6, 17],
        noEffectTo: [8],
        notAffectedBy: [],
    },
    {
        id: 4,
        name: "types.ground",
        description: "types.groundDesc",
        effective: [9, 12, 3, 5, 8],
        weak: [10, 11, 14],
        notEffective: [11, 6],
        resists: [3, 5],
        noEffectTo: [2],
        notAffectedBy: [12],
    },
    {
        id: 5,
        name: "types.rock",
        description: "types.rockDesc",
        effective: [9, 14, 6, 2],
        weak: [10, 11, 1, 8, 4],
        notEffective: [1, 4, 8],
        resists: [0, 9, 3, 2],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 6,
        name: "types.bug",
        description: "types.bugDesc",
        effective: [11, 13, 16],
        weak: [9, 2, 5],
        notEffective: [9, 1, 3, 2, 7, 8, 17],
        resists: [11, 1, 4],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 7,
        name: "types.ghost",
        description: "types.ghostDesc",
        effective: [13, 7],
        weak: [7, 16],
        notEffective: [16],
        resists: [3, 6],
        noEffectTo: [0],
        notAffectedBy: [0, 1],
    },
    {
        id: 8,
        name: "types.steel",
        description: "types.steelDesc",
        effective: [5, 14, 17],
        weak: [9, 1, 4],
        notEffective: [10, 11, 12, 8],
        resists: [0, 11, 14, 2, 13, 6, 5, 15, 8, 17],
        noEffectTo: [],
        notAffectedBy: [3],
    },
    {
        id: 9,
        name: "types.fire",
        description: "types.fireDesc",
        effective: [11, 14, 6, 8],
        weak: [10, 4, 5],
        notEffective: [9, 10, 5, 15],
        resists: [9, 11, 14, 6, 8, 17],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 10,
        name: "types.water",
        description: "types.waterDesc",
        effective: [9, 4, 5],
        weak: [11, 12],
        notEffective: [10, 11, 15],
        resists: [9, 10, 14, 8],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 11,
        name: "types.grass",
        description: "types.grassDesc",
        effective: [10, 5, 4],
        weak: [9, 6, 14, 3, 2],
        notEffective: [9, 11, 3, 2, 6, 15, 8],
        resists: [10, 12, 11, 4],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 12,
        name: "types.electric",
        description: "types.electricDesc",
        effective: [10, 2],
        weak: [4],
        notEffective: [12, 11, 15],
        resists: [2, 12, 8],
        noEffectTo: [4],
        notAffectedBy: [],
    },
    {
        id: 13,
        name: "types.psychic",
        description: "types.psychicDesc",
        effective: [1, 3],
        weak: [6, 7, 16],
        notEffective: [13, 8],
        resists: [1, 13],
        noEffectTo: [16],
        notAffectedBy: [],
    },
    {
        id: 14,
        name: "types.ice",
        description: "types.iceDesc",
        effective: [11, 4, 2, 15],
        weak: [1, 9, 5, 8],
        notEffective: [9, 10, 14, 8],
        resists: [14],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 15,
        name: "types.dragon",
        description: "types.dragonDesc",
        effective: [15],
        weak: [14, 15, 17],
        notEffective: [8],
        resists: [9, 10, 11, 12],
        noEffectTo: [17],
        notAffectedBy: [],
    },
    {
        id: 16,
        name: "types.dark",
        description: "types.darkDesc",
        effective: [13, 7],
        weak: [1, 6, 17],
        notEffective: [1, 16, 17],
        resists: [7, 16],
        noEffectTo: [],
        notAffectedBy: [13],
    },
    {
        id: 17,
        name: "types.fairy",
        description: "types.fairyDesc",
        effective: [1, 15, 16],
        weak: [3, 8],
        notEffective: [9, 3, 8],
        resists: [1, 6, 16],
        noEffectTo: [],
        notAffectedBy: [15],
    },
]