import type { PkmnType } from "./interfaces";

export const types: PkmnType[] = [
    {
        id: 0,
        name: "normal",
        description: "Neutral attacks, regular people",
        effective: [],
        weak: [1],
        notEffective: [5, 8],
        resists: [],
        noEffectTo: [7],
        notAffectedBy: [7],
    },
    {
        id: 1,
        name: "fighting",
        description: "Fights, martial arts, honor, justice",
        effective: [0, 14, 5, 16, 8],
        weak: [2, 13, 17],
        notEffective: [3, 2, 13, 6, 17],
        resists: [6, 5, 16],
        noEffectTo: [7],
        notAffectedBy: [],
    },
    {
        id: 2,
        name: "flying",
        description: "Flying beings (mostly birds), air",
        effective: [6, 11, 1],
        weak: [14, 5, 12],
        notEffective: [12, 5, 8],
        resists: [11, 1, 6],
        noEffectTo: [],
        notAffectedBy: [4],
    },
    {
        id: 3,
        name: "poison",
        description: "Poison, venom, chemical debris, toxins, pollution",
        effective: [11, 17],
        weak: [4, 13],
        notEffective: [3, 4, 5, 7],
        resists: [11, 1, 3, 6, 17],
        noEffectTo: [8],
        notAffectedBy: [],
    },
    {
        id: 4,
        name: "ground",
        description: "Ground, sand, dirt",
        effective: [9, 12, 3, 5, 8],
        weak: [10, 11, 14],
        notEffective: [11, 6],
        resists: [3, 5],
        noEffectTo: [2],
        notAffectedBy: [12],
    },
    {
        id: 5,
        name: "rock",
        description: "Rocks",
        effective: [9, 14, 6, 2],
        weak: [10, 11, 1, 8],
        notEffective: [1, 4, 8],
        resists: [0, 9, 3, 2],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 6,
        name: "bug",
        description: "Bugs",
        effective: [11, 13, 16],
        weak: [9, 2, 5],
        notEffective: [9, 1, 3, 2, 7, 8, 17],
        resists: [11, 1, 4],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 7,
        name: "ghost",
        description: "Ghosts, spirits, undead, supernatural forces",
        effective: [13, 7],
        weak: [7, 16],
        notEffective: [16],
        resists: [3, 6],
        noEffectTo: [0],
        notAffectedBy: [0, 1],
    },
    {
        id: 8,
        name: "steel",
        description: "Steel and other metals, machinery, electronics, mechanisms",
        effective: [5, 14, 17],
        weak: [9, 1, 4],
        notEffective: [10, 11, 12, 8],
        resists: [0, 11, 14, 2, 13, 6, 5, 15, 8, 17],
        noEffectTo: [],
        notAffectedBy: [3],
    },
    {
        id: 9,
        name: "fire",
        description: "Fire, heat",
        effective: [11, 14, 6, 8],
        weak: [10, 4, 5],
        notEffective: [9, 10, 5, 15],
        resists: [9, 11, 14, 6, 8, 17],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 10,
        name: "water",
        description: "Water, rain, steam",
        effective: [9, 4, 5],
        weak: [11, 12],
        notEffective: [10, 11, 15],
        resists: [9, 10, 14, 8],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 11,
        name: "grass",
        description: "Plants, seeds",
        effective: [10, 5, 4],
        weak: [9, 6, 14, 3, 2],
        notEffective: [9, 11, 3, 2, 6, 15, 8],
        resists: [10, 12, 11, 4],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 12,
        name: "electric",
        description: "Electricity",
        effective: [10, 2],
        weak: [4],
        notEffective: [12, 11, 15],
        resists: [2, 12, 8],
        noEffectTo: [4],
        notAffectedBy: [],
    },
    {
        id: 13,
        name: "psychic",
        description: "Mind, psychic powers",
        effective: [1, 3],
        weak: [6, 7, 16],
        notEffective: [13, 8],
        resists: [1, 13],
        noEffectTo: [16],
        notAffectedBy: [],
    },
    {
        id: 14,
        name: "ice",
        description: "Ice, snow, hail, cold temperatures",
        effective: [11, 4, 2, 15],
        weak: [9, 5],
        notEffective: [9, 10, 14, 8],
        resists: [14],
        noEffectTo: [],
        notAffectedBy: [],
    },
    {
        id: 15,
        name: "dragon",
        description: "Dragons",
        effective: [15],
        weak: [14, 15, 17],
        notEffective: [8],
        resists: [9, 10, 11, 12],
        noEffectTo: [17],
        notAffectedBy: [],
    },
    {
        id: 16,
        name: "dark",
        description: "Dishonesty, tricks and cheats, evil, darkness",
        effective: [13, 7],
        weak: [1, 6, 17],
        notEffective: [1, 16, 17],
        resists: [7, 16],
        noEffectTo: [],
        notAffectedBy: [13],
    },
    {
        id: 17,
        name: "fairy",
        description: "Fairies, light, magic",
        effective: [1, 15, 16],
        weak: [3, 8],
        notEffective: [9, 3, 8],
        resists: [1, 6, 16],
        noEffectTo: [],
        notAffectedBy: [15],
    },
]